-- react 기본 게시판 프로젝트
CREATE TABLE REACT_BOARD (
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(100)
	, BOARD_WRITER VARCHAR(30) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO REACT_BOARD (
	BOARD_TITLE
	, BOARD_CONTENT
	, BOARD_WRITER
) VALUES (
	'두번째 게시글'
	, '내용입니다'
	, '김자바'
);