
CREATE TABLE REACT_STUDENT (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
		, STU_NAME VARCHAR(30) NOT NULL
		, KOR_SCORE INT
		, ENG_SCORE INT
		, MATH_SCORE INT
		, STU_AGE INT
		, STU_TEL VARCHAR(20) UNIQUE
		, STU_ADDR VARCHAR(50)
);
SELECT * FROM REACT_STUDENT;

INSERT INTO REACT_STUDENT VALUES (1, "JAVA", 70, 80, 90, 20, "010-1111-2222", "울산");