
CREATE TABLE REACT_STUDENT (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
		, STU_NAME VARCHAR(30) NOT NULL
		, KOR_SCORE INT
		, ENG_SCORE INT
		, MATH_SCORE INT
		, STU_AGE INT
		, STU_TEL VARCHAR(20) UNIQUE
		, STU_ADDR VARCHAR(50)
);
SELECT * FROM react_student;

INSERT INTO react_student (STU_NAME, KOR_SCORE, ENG_SCORE, MATH_SCORE)
VALUES ("테스트", 50, 60, 70);

SELECT STU_NUM
	, STU_NAME
	, KOR_SCORE
	, ENG_SCORE
	, MATH_SCORE
	, (KOR_SCORE + ENG_SCORE + MATH_SCORE) / 3 AS AVG
FROM react_student;

INSERT INTO REACT_STUDENT VALUES (1, "JAVA", 70, 80, 90, 20, "010-1111-2222", "울산");

